import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { cn } from "@/lib/utils";
import Blob from "./components/Blob";

const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(outfit.className, "background w-full")}>
        <div className="relative">
          <div className="absolute -top-14 right-24 blur-[100px]">
            <Blob />
          </div>
          <div className="absolute -top-80 right-20 rotate-180 blur-[100px]">
            <Blob />
          </div>
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
